
project_id = "vqkxrbflwhunvbotjdds"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
port = 9999

[storage]
enabled = true
port = 5000

[functions]
[functions.store_webauthn_challenge]
verify_jwt = true

[functions.webauthn-registration-options]
verify_jwt = true

[functions.webauthn-registration-verification]
verify_jwt = true

[functions.webauthn-authentication-options]
verify_jwt = true

[functions.webauthn-authentication-verification]
verify_jwt = true

