
# This file defines config for your edge functions.
project_id = "vqkxrbflwhunvbotjdds"

[functions.rate-limiter]
verify_jwt = true

[functions.impersonate-user]
verify_jwt = true

[functions.restore-admin]
verify_jwt = true
